kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: "<IP TO BE MODIFIED>"
  KUBERNETES_SERVICE_PORT: "<PORT TO BE MODIFIED"
