apiVersion: v1
kind: Service
metadata:
  name: svc-podinfo
  labels:
    run: svc-podinfo
spec:
  type: ClusterIP
  #type: NodePort
  #type: LoadBalancer
  #externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 9898
    protocol: TCP
  selector:
    run: podinfo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-podinfo
spec:
  selector:
    matchLabels:
      run: podinfo
  replicas: 2
  template:
    metadata:
      labels:
        run: podinfo
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo
        ports:
        - containerPort: 9898
